[rpc]
    channel_listen_ip=0.0.0.0
    channel_listen_port=20203
    jsonrpc_listen_ip=127.0.0.1
    jsonrpc_listen_port=8548
    disable_dynamic_group=false
[p2p]
    listen_ip=0.0.0.0
    listen_port=30303
    ; nodes to connect
    node.0=127.0.0.1:30300
    node.1=127.0.0.1:30301
    node.2=127.0.0.1:30302
    node.3=127.0.0.1:30303
    

[certificate_blacklist]
    ; crl.0 should be nodeid, nodeid's length is 128
    ;crl.0=

[certificate_whitelist]
    ; cal.0 should be nodeid, nodeid's length is 128
    ;cal.0=

[group]
    group_data_path=data/
    group_config_path=conf/

[network_security]
    ; directory the certificates located in
    data_path=conf/
    ; the node private key file
    key=gmnode.key
    ; the node certificate file
    cert=gmnode.crt
    ; the ca certificate file
    ca_cert=gmca.crt

[chain]
    id=1
    ; use SM crypto or not, should nerver be changed
    sm_crypto=true
    sm_crypto_channel=true
    rsa_crypto_channel=true

[compatibility]
    ; supported_version should nerver be changed
    supported_version=2.11.0

[log]
    enable=true
    ; the log path, default path is ./log
    log_path=./log
	; print the log to std::cout or not, default print to the log files
    enable_console_output = false
    ; enable/disable the statistics function
    enable_statistic=false
    ; network statistics interval, unit is second, default is 60s
    stat_flush_interval=60
    ; info debug trace
    level=info
    ; MB
    max_log_file_size=200
    flush=true

[flow_control]
    ; restrict QPS of the node
    ;limit_req=1000
    ; restrict the outgoing bandwidth of the node
    ; Mb, can be a decimal
    ; when the outgoing bandwidth exceeds the limit, the block synchronization operation will not proceed
    ;outgoing_bandwidth_limit=2






[storage_security]
enable=true
key_manager_ip=127.0.0.1
key_manager_port=8150
cipher_data_key=c853d1560d26432c4bf328f9c918e0a519341e0f962d1b412aa3cbd572f976c786736a7964f7ca093c3515479818326072469a3ff9d3de3b8fcd1ac764e302435674cb5816027dd026833744c78959f0
